apiVersion: v1
kind: Service
metadata:
  name: watchdog-backend
  namespace: watchdog-system
  labels:
    app.kubernetes.io/name: watchdog-backend
    app.kubernetes.io/part-of: watchdog-system
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: watchdog-backend

---
apiVersion: v1
kind: Service
metadata:
  name: watchdog-frontend
  namespace: watchdog-system
  labels:
    app.kubernetes.io/name: watchdog-frontend
    app.kubernetes.io/part-of: watchdog-system
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: watchdog-frontend
